export const MODE = {
  LIGHT: 'light',
  DARK: 'dark',
};
export const baseTheme = {
  AMARANTH: '#00D9CF',
  SHADOW: '#000000',
  PLACEHOLDER: '#BFBFBF',
  ERROR: '#FF0000',
  WARNING: '#FFF000',
  LINK: '#2196f3',
  NUMBERS_RANK_LIST: '#1D1D1D',
};

export const lightTheme = {
  STATUS_BAR: '#00D9AA',

  BACKGROUND_MAIN: '#F5F6F9',
  BACKGRAND_BOX: '#FFFFFF',
  BACKGRAND_INTRO_LANGUAGE_DROP: '#DFDFDF',
  BACKGRAND_TOOLBAR: '#FFFFFF',
  BACKGRAND_ACTION_BUTTON: '#1abc9c',

  PAGINATION_DOT_ACTIVE: '#23B3BE',
  PAGINATION_DOT_INACTIVE: '#D7DBE6',

  TEXT_TITLE: '#395674',
  TEXT_SUBTITLE: '#707070',
  TEXT_PARAGRAPH: '#ADB5CC',
  TEXT_COLOR: '#34495E',

  BORDER_BOX: '#D7DBE6',
  BORDER_TEXTINPUT: '#D7DBE6',

  BUTTON_ACTIVE: '#23B3BE',
  BUTTON_DIACTIVE: '#B8C1D9',

  BUTTON_TEXT: '#FFFFFF',

  MENU_ICON_TINT: '#2ECC71',
};

export const darkTheme = {
  STATUS_BAR: '#FFFFFF00',

  BACKGROUND_MAIN: '#23394F',
  BACKGRAND_BOX: '#34495E',
  BACKGRAND_INTRO_LANGUAGE_DROP: '#546E7A',
  BACKGRAND_TOOLBAR: '#34495E',
  BACKGRAND_ACTION_BUTTON: '#1abc9c',

  PAGINATION_DOT_ACTIVE: '#00ADC1',
  PAGINATION_DOT_INACTIVE: '#D7DBE6',

  TEXT_TITLE: '#ECEFF1',
  TEXT_SUBTITLE: '#B0BDC4',
  TEXT_PARAGRAPH: '#B0BDC4',
  TEXT_COLOR: '#FFFFFF',

  BORDER_BOX: '#FFFFFF22',
  BORDER_TEXTINPUT: '#D7DBE6',

  BUTTON_ACTIVE: '#23B3BE',
  BUTTON_DIACTIVE: '#B8C1D9',

  BUTTON_TEXT: '#FFFFFF',

  MENU_ICON_TINT: '#2ECC71',
};
